[features]
seeds = false
skip-lint = false

[programs.localnet]
vaults = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/hoak/.config/solana/id.json"